# Generated by Django 5.2.7 on 2025-10-30 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='detailed_description',
            field=models.TextField(null=True, verbose_name='Детальное описание'),
        ),
    ]
