# Generated by Django 5.2.7 on 2025-10-30 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_tasks_detailed_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='detailed_description',
            field=models.TextField(blank=True, null=True, verbose_name='Детальное описание'),
        ),
    ]
